### ISSUE TITLE
XVFB failed to start?

### ISSUE THREAD

**Issue by yamikuronue** [blueimp/chromedriver#1]
I'm having an issue where sometimes the container just doesn't start up; it exits with `xvfb-run: error: Xvfb failed to start`

I'm running with the following block in my docker-compose:
```
  selenium:
    image: blueimp/chromedriver
    environment:
      - VNC_ENABLED=false
      - EXPOSE_X11=false
    ports:
      - 5900:5900
```

(I am trying to get the test working before I use any video stuff, but I may need to swap back to the official selenium chrome image at this rate)

I'm running docker on a local CentOS VM, if that matters.
