### ISSUE TITLE
nginx cannot store uploaded files (?)

### ISSUE THREAD

**Issue by drjayvee** [blueimp/chromedriver#6]
I'm using [Lando](https://lando.dev) to launch chromedriver as a [custom container](https://docs.lando.dev/config/compose.html), so I'm not sure whether this affects all users.

What I did find is that file uploads (used to simulate `<input type="file">`) stopped working, since user `webdriver` cannot write to `/var/lib/nginx/body/`, which is owned by `root`.

Here are the relevant container logs
```
webdriver_1   | 192.168.48.2 - - [24/Sep/2021:14:30:23 +0000] "POST /session/acea6a72c11e91cd6d3ea61b79b54dcd/element/c0822b9a-b4e5-4249-8c4f-05ed1b55c35f/element HTTP/1.1" 200 88 "-" "-"
webdriver_1   | 2021/09/24 14:30:45 [crit] 54#54: *3 open() "/var/lib/nginx/body/0000000001" failed (13: Permission denied), client: 192.168.48.2, server: , request: "POST /session/acea6a72c11e91cd6d3ea61b79b54dcd/file HTTP/1.1", host: "webdriver:4444"
webdriver_1   | 192.168.48.2 - - [24/Sep/2021:14:30:45 +0000] "POST /session/acea6a72c11e91cd6d3ea61b79b54dcd/file HTTP/1.1" 500 177 "-" "-"
```

Maybe `RUN chown webdriver:webdriver /var/lib/nginx/body/` or similar in `Dockerfile` can fix this generally?

I fixed the problem with the following Lando configuration:
```yaml
services:
  webdriver:
    type: compose
    app_mount: false
    services:
      image: blueimp/chromedriver:latest
      # https://docs.lando.dev/config/compose.html#setting-the-command
      # https://github.com/blueimp/chromedriver/blob/master/Dockerfile
      command: entrypoint reverse-proxy /usr/local/bin/chromedriver --port=5555
      environment:
        - ENABLE_VNC=true
        - VNC_PASSWORD=hi
        - SCREEN_WIDTH=1440
        - SCREEN_HEIGHT=900
      ports:
        - 5900:5900  # VNC viewer (HTTP need not be exposed externally)
    run_as_root:
      # Make sure nginx can store uploaded files
      - chown webdriver:webdriver /var/lib/nginx/body/
```
